### PR TITLE
Add test for forest inference running on Triton + handle Tensor in Op Runner

### PR DESCRIPTION
**Pull request by oliverholworthy**
- Correct handling of Tensors returned by Operators using `OperatorRunner`
- Adds integration test for forest inference operator running on Triton.

### CODE REVIEW

**Comment by karlhigley** [comment]
I think we're either going to have to install xgboost in CPU CI or improve how we handle optional dependencies in the tests. (We're going to have a lot more optional dependencies, so maybe both.)

**Comment by oliverholworthy** [comment]
@jperez999 please can you help look into adding xgboost to the Jenkins setup for this?

**Comment by jperez999** [comment]
rerun tests

**Comment by oliverholworthy** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Pull request merged**
