### PR TITLE
update broken link

### PR DESCRIPTION
**Pull request by andompesta**
Sorry to jump in without any real reason.

But it appears that the tutorial link was broken. Hopefully I put the correct link in place

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]
Thanks for the fix!

**Comment by andompesta** [comment]
It seems tritonserver tests are failing. But it seems odd given the change

**Comment by karlhigley** [comment]
Probably an unrelated issue somewhere in the repo, we'll re-run the tests once we figure out what it is

**Comment by andompesta** [comment]
close this as the examples have been migrated into Merlin repo

**Pull request closed without merging**
