### PR TITLE
Nvt local runtime

### PR DESCRIPTION
**Pull request by jperez999**
This allows for the use of nvtabular workflows with the local runtime. it requires changes to core in the PR: https://github.com/NVIDIA-Merlin/core/pull/180

### CODE REVIEW

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
It seems like this is hitting dtype issues related to the difference between actual scalars and lists of one element. Wondering what it would take to make a clearer distinction between those two cases. Do we have to sort out shapes?

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Comment by jperez999** [comment]
rerun tests

**Pull request merged**
