### PR TITLE
use tox for github CI steps

### PR DESCRIPTION
**Pull request by nv-alaiacano**
This is the first step to consolidate some of our CI configuration so that it is in one place per repository. We'll start with the systems package and see how it goes.

We'll use tox to configure python environments for installing dependencies and executing tests. One for CPU, one for GPU, and a common one for linting checks.

In particular, this PR:

* Introduces `tox.ini` to set up a test environment and run tests and linting
* Adds new requirements files:
  * `requirements-test.txt` - common libraries needed to run tests
  * `requirements-test-cpu.txt` - cpu-specific versions of things like faiss and tensorflow
  * `requirements-test-gpu.txt` (will be used by jenkins/blossom) - gpu-specific versions of things like faiss and tensorflow 

When running tests, tox will install `requirements-test-[cg]pu.txt` and execute pytest commands.

Running `tox -e cpu-test` and `tox -e lint` both work on my local machine and should work in the github action that has been modified to use these commands. We'll see!

# Update

* I couldn't get the docs to build in tox. The tox env is still there in `tox.ini` but it is not used in the `cpu-ci.yml` github workflow.
* I actually couldn't get sphinx working completely _at all_ due to failed import issues like `WARNING: [autosummary] failed to import 'merlin.systems.dag.Ensemble': no module named merlin.systems.dag.Ensemble`.
* I also split out a `requirements-docs.txt` file so that we can just install those in the github actions vm.

### CODE REVIEW

**Comment by nv-alaiacano** [comment]
Heads up that this might be a little noisy as I figure out all of the github actions! Sorry all.

**Comment by nv-alaiacano** [comment]
rerun tests

**Review by karlhigley — APPROVED** [review]

**Review by oliverholworthy — APPROVED** [review]

**Comment by nv-alaiacano** [comment]
This PR breaks the automatic documentation generation for most classes.

However - there wasn't really anything there before (see [here](https://nvidia-merlin.github.io/systems/review/pr-159/api.html)). I'm going to merge this PR and work on the documentation fix in a new one.

**Comment by nv-alaiacano** [comment]
rerun tests

**Comment by nv-alaiacano** [comment]
rerun tests

**Pull request merged**
